export const SELECT_COMPLAINT = 'SELECT_COMPLAINT';
export const ACCEPT_COMPLAINT_SUCCESS = 'ACCEPT_COMPLAINT_SUCCESS';
export const REJECT_COMPLAINT_SUCCESS = 'REJECT_COMPLAINT_SUCCESS';
export const FORWARD_COMPLAINT_SUCCESS = 'FORWARD_COMPLAINT_SUCCESS';
export const REASSIGN_COMPLAINT_SUCCESS = 'REASSIGN_COMPLAINT_SUCCESS';
export const COMPLAINT_ERROR = 'COMPLAINT_ERROR';
